//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationTable
    {
        public int id_application { get; set; }
        public Nullable<System.DateTime> opening_date { get; set; }
        public string problem_description { get; set; }
        public Nullable<int> id_equipment { get; set; }
        public Nullable<int> id_malfunction { get; set; }
        public Nullable<int> id_client { get; set; }
        public Nullable<int> id_executor { get; set; }
        public Nullable<int> id_status { get; set; }
        public Nullable<decimal> total_cost { get; set; }
        public Nullable<System.DateTime> closing_date { get; set; }
    
        public virtual MalfunctionTable MalfunctionTable { get; set; }
        public virtual EquipmentTable EquipmentTable { get; set; }
        public virtual UserTable UserTable { get; set; }
        public virtual StatusTable StatusTable { get; set; }
    }
}
