//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Demo_examEntities : DbContext
    {
        public Demo_examEntities()
            : base("name=Demo_examEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationTable> ApplicationTable { get; set; }
        public virtual DbSet<EquipmentTable> EquipmentTable { get; set; }
        public virtual DbSet<MalfunctionTable> MalfunctionTable { get; set; }
        public virtual DbSet<RoleTable> RoleTable { get; set; }
        public virtual DbSet<SparePartTable> SparePartTable { get; set; }
        public virtual DbSet<StatusTable> StatusTable { get; set; }
        public virtual DbSet<UserTable> UserTable { get; set; }
    }
}
