//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SparePartTable
    {
        public int id_spare_part { get; set; }
        public string name_spare_part { get; set; }
        public Nullable<int> id_equipment { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<int> availability { get; set; }
    
        public virtual EquipmentTable EquipmentTable { get; set; }
    }
}
