//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Запчасти
    {
        public int id_запчасти { get; set; }
        public string Название_запчасти { get; set; }
        public Nullable<int> id_оборудования { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
        public Nullable<int> Наличие_шт { get; set; }
    
        public virtual Оборудование Оборудование { get; set; }
    }
}
