//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявки
    {
        public int id_заявки { get; set; }
        public Nullable<System.DateTime> Дата_открытия { get; set; }
        public string Описание_проблемы { get; set; }
        public Nullable<int> id_оборудования { get; set; }
        public Nullable<int> id_неисправности { get; set; }
        public Nullable<int> id_клиента { get; set; }
        public Nullable<int> id_исполнителя { get; set; }
        public Nullable<int> id_статуса { get; set; }
        public Nullable<decimal> Итоговая_стоимость { get; set; }
        public Nullable<System.DateTime> Дата_закрытия { get; set; }
    
        public virtual Неисправности Неисправности { get; set; }
        public virtual Оборудование Оборудование { get; set; }
        public virtual Пользователи Пользователи { get; set; }
        public virtual Статус Статус { get; set; }
    }
}
